[publisher]

provider_engine = 'amnis'

product_update_interval_secs = 10
health_check_port = 8000

health_check_threshold_secs = 60

[publisher.pythd]
endpoint = 'ws://127.0.0.1:8910'

[publisher.amnis]
update_interval_secs = 1
confidence_ratio_bps = 10
node_url = 'https://fullnode.amnis.finance/v1'
http_endpoint = "https://api.pythtest.pyth.network"
ws_endpoint = "wss://api.pythtest.pyth.network"
first_mapping = 'AFmdnt9ng1uVxqCmqwQJDAYC5cKTkw8gJKSM5PnzuF6z'
program_key = '8tfDNiaEyrV6Q1U4DEXrEigs9DoDtkugzFbybENEbCDz'
